/**
 * Candidate Report Card Route
 * Google Service: Gemini API
 * Generates an AI-powered public profile/report card for a candidate
 */
const express = require('express');
const router = express.Router();
const { aiLimiter } = require('../middleware/rateLimit');

let GoogleGenerativeAI;
try { ({ GoogleGenerativeAI } = require('@google/generative-ai')); } catch { /* optional */ }

const CANDIDATE_PROMPT = `You are an expert Indian political analyst and fact-checker with deep knowledge of Indian elections, ECI records, and public affidavits.

A voter wants to know about a political candidate before voting. Based on the candidate name and constituency provided, generate a structured report card using publicly available information, general knowledge about Indian politics, and ECI affidavit data patterns.

Return ONLY a valid JSON object with this EXACT structure:
{
  "name": "<candidate full name>",
  "constituency": "<constituency name>",
  "party": "<political party name or 'Independent'>",
  "position": "<current/past position, e.g., 'MP - Lok Sabha', 'MLA', 'First-time candidate'>",
  "education": "<highest qualification>",
  "age": "<approximate age or 'Unknown'>",
  "experience": "<years of political experience>",
  "criminalCases": <number of declared criminal cases, 0 if none>,
  "criminalDetails": "<brief description of cases if any, or 'No criminal cases declared'>",
  "assetsValue": "<declared assets value in crores, e.g., '₹2.3 Cr' or 'Not available'>",
  "previousTerms": "<number of previous terms as elected representative>",
  "keyAchievements": ["<achievement 1>", "<achievement 2>", "<achievement 3>"],
  "redFlags": ["<concern 1>", "<concern 2>"],
  "positives": ["<positive 1>", "<positive 2>", "<positive 3>"],
  "overallRating": <number 1-10 based on public record and track record>,
  "ratingReason": "<2-sentence reason for the rating>",
  "verifyLinks": ["https://affidavit.eci.gov.in", "https://myneta.info", "https://eci.gov.in"],
  "disclaimer": "This report is generated by AI based on publicly available data. Always verify information at affidavit.eci.gov.in before voting.",
  "dataConfidence": "HIGH" | "MEDIUM" | "LOW"
}

If you don't have specific information about this candidate, use your best knowledge about the party, region, and context. Always be factual, unbiased, and neutral. Never make up criminal cases if you don't know of any. Always return valid JSON only.`;

/**
 * POST /api/candidate
 * @body {string} name - Candidate name
 * @body {string} constituency - Constituency name
 * @body {string} state - State name
 */
router.post('/', aiLimiter, async (req, res) => {
  try {
    const { name, constituency, state } = req.body;

    if (!name || !constituency) {
      return res.status(400).json({ error: 'Candidate name and constituency are required' });
    }
    if (name.trim().length < 2) {
      return res.status(400).json({ error: 'Please enter a valid candidate name' });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || !GoogleGenerativeAI) {
      // Demo response
      return res.json({
        name: name.trim(),
        constituency: constituency.trim(),
        party: 'Sample Party',
        position: 'MP - Lok Sabha',
        education: 'B.A. Political Science',
        age: '52',
        experience: '15 years',
        criminalCases: 2,
        criminalDetails: 'Demo mode: Add your Gemini API key to see real AI-generated analysis.',
        assetsValue: '₹4.2 Cr',
        previousTerms: 2,
        keyAchievements: [
          'Built 3 government schools in constituency',
          'Raised issues of farmers in Parliament',
          'Led infrastructure development projects',
        ],
        redFlags: [
          'Two pending criminal cases (IPC Sections 147, 353)',
          'Assets grew 300% between terms',
        ],
        positives: [
          'Strong attendance record in Parliament (85%+)',
          'Actively engaged with constituents',
          'No corruption charges',
        ],
        overallRating: 6,
        ratingReason: 'Demo rating. Real AI analysis will evaluate the candidate\'s actual public record, criminal background, and achievements.',
        verifyLinks: ['https://affidavit.eci.gov.in', 'https://myneta.info', 'https://eci.gov.in'],
        disclaimer: 'This report is generated by AI based on publicly available data. Always verify information at affidavit.eci.gov.in before voting.',
        dataConfidence: 'LOW',
        isDemo: true,
      });
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-lite' });

    const prompt = `${CANDIDATE_PROMPT}\n\nGenerate a report card for:\nCandidate Name: "${name.trim()}"\nConstituency: "${constituency.trim()}"${state ? `\nState: "${state}"` : ''}`;

    const result = await model.generateContent(prompt);
    const raw = result.response.text();

    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error('Invalid AI response format');

    const report = JSON.parse(jsonMatch[0]);

    res.json({ ...report, timestamp: new Date().toISOString() });
  } catch (err) {
    console.error('[Candidate] Error:', err.message);
    res.status(500).json({
      error: 'Report generation failed',
      details: err.message,
    });
  }
});

module.exports = router;
